spring.datasource.url=jdbc:postgresql://localhost:5432/universidad_db
spring.datasource.username=postgres
spring.datasource.password=yael
eureka.client.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

openai.api.key=${OPENAI_API_KEY:}

server.port=8080
